### ISSUE TITLE
ERROR / getWebApi(): Error retrieving smartlocks: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by ymurawski** [iobroker-community-adapters/ioBroker.nuki-extended#280]
Hi, i set up Nuki extended today and created and WEB API Token under https://web.nuki.io/#/pages/web-api / API Token- Generate API Token and gave it all rights.

Then i entered it in the Iobroker instance. 
But it just shows me my Bridge and not any opener or Door Lock.
in Log it says getWebApi(): Error retrieving smartlocks: Cannot read properties of undefined (reading 'toLowerCase')

Any ideas ?

**Comment by micudaj** [comment]
I have the same issue

**Comment by ymurawski** [comment]
> I have the same issue

Update the adapter via the guthup repository... The cat symbol... They didn't update the adapter in iobroker to the latest release

**Comment by mcm1957** [comment]
@ymurawski 

Please always add the minimum required infos:

Version of adapter:
Js-controlelr Version:
Node Version:

If the problem is solved with 2.6.5 please let us know.

**Comment by M1cS0w** [comment]
Hello I got the same issue.

Yesterday with:

`
📷
nuki-extended.0
2024-04-20 22:20:18.241warngetWebApi(): Error retrieving notifications: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
📷
nuki-extended.0
2024-04-20 22:18:29.162warngetWebApi(): Error retrieving smartlocks: 500 - "<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
`

And now:

`
nuki-extended.0 | 2024-04-21 14:21:06.985 | warn | getWebApi(): Error retrieving smartlocks: Error: getaddrinfo ENOTFOUND api.nuki.io
-- | -- | -- | --
nuki-extended.0 | 2024-04-21 14:21:06.984 | warn | getWebApi(): Error retrieving notifications: Error: getaddrinfo ENOTFOUND api.nuki.io
`

admin version: v6.13.16
Node.JS: v18.20.2
NPM: 10.5.0
Linux virtual machine: debian 12 bookworm

Since this two issues, I only change on my Unifi Dream Machine Pro the network safety for DNS shield on automatic. Ad Blocking is still on the network active. I had idea, that this could be a ad blocking problem, but this isn't.

**Comment by weindler** [comment]
The same here: `getWebApi(): Error retrieving users: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"`

**Comment by mcm1957** [comment]
This problem is most likely due to problem at nuki service:

https://developer.nuki.io/t/lots-of-errors-when-using-web-api-or-https-web-nuki-io/31173
https://status.nuki.io/en/

![image](https://github.com/user-attachments/assets/e1b1ef8a-5727-456f-bc8d-0735336db45f)

**Comment by mcm1957** [comment]
Please open a new issue if problem still exists after nuki reports full functionality.
